name: End-to-end tests

# Declare default permissions as read only.
permissions: read-all

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/container-image.yml
    permissions:
      packages: write
    with:
      push-image: false
  run-e2e-tests:
    name: "Tests"
    needs: [build]
    uses: kubewarden/kubewarden-end-to-end-tests/.github/workflows/e2e-tests.yml@main
    with:
      audit-scanner-image-repository: ${{ needs.build.outputs.repository }}
      audit-scanner-image-tag: ${{ needs.build.outputs.tag }}
      audit-scanner-image-artifact: ${{ needs.build.outputs.artifact }}
